# -*- coding: utf-8 -*-
"""Attendance Analyzer Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZVs7WWQ6DNqniGT86f-xdx41EiIv6G8K
"""

# STEP 1: Setup folders and sample data
import os

# Create folder structure
base_path = "Attendance_Tracker"
os.makedirs(f"{base_path}/logs", exist_ok=True)
os.makedirs(f"{base_path}/output", exist_ok=True)

# Create students.csv
with open(f"{base_path}/students.csv", "w") as f:
    f.write("ID,Name,ExpectedTime\n")
    f.write("1,Aarav,09:00\n")
    f.write("2,Ananya,09:00\n")
    f.write("3,Charu,09:00\n")
    f.write("4,Divya,09:00\n")
    f.write("5,Gaurav,09:00\n")
    f.write("6,Iyra,09:00\n")

# Log for 2025-06-20
with open(f"{base_path}/logs/2025-06-20.csv", "w") as f:
    f.write("ID,Timestamp\n")
    f.write("1,2025-06-20 08:55\n")
    f.write("2,2025-06-20 09:10\n")
    f.write("4,2025-06-20 09:20\n")
    f.write("5,2025-06-20 09:00\n")
    f.write("6,2025-06-20 08:58\n")

# Log for 2025-06-21
with open(f"{base_path}/logs/2025-06-21.csv", "w") as f:
    f.write("ID,Timestamp\n")
    f.write("1,2025-06-21 09:00\n")
    f.write("3,2025-06-21 08:50\n")
    f.write("4,2025-06-21 08:55\n")
    f.write("5,2025-06-21 09:20\n")
    f.write("2,2025-06-21 09:08\n")

# Log for 2025-06-22
with open(f"{base_path}/logs/2025-06-22.csv", "w") as f:
    f.write("ID,Timestamp\n")
    f.write("1,2025-06-22 09:00\n")
    f.write("2,2025-06-22 08:55\n")
    f.write("3,2025-06-22 09:10\n")
    f.write("4,2025-06-22 09:05\n")
    f.write("5,2025-06-22 09:00\n")
    f.write("6,2025-06-22 08:58\n")

import pandas as pd
from datetime import datetime

def analyze_attendance_for_date(date_str):
    student_path = f"{base_path}/students.csv"
    log_path = f"{base_path}/logs/{date_str}.csv"
    output_path = f"{base_path}/output/{date_str}_attendance.csv"

    if not os.path.exists(log_path):
        print(f"❌ Log missing for {date_str}")
        return

    students = pd.read_csv(student_path)
    logs = pd.read_csv(log_path)
    logs['Timestamp'] = pd.to_datetime(logs['Timestamp'])

    results = []

    for _, student in students.iterrows():
        sid = student['ID']
        name = student['Name']
        expected = datetime.strptime(student['ExpectedTime'], "%H:%M").time()

        log_record = logs[logs['ID'] == sid]
        if not log_record.empty:
            arrival = log_record.iloc[0]['Timestamp'].time()
            if arrival <= expected:
                status = "Present"
            elif arrival <= datetime.strptime("10:00", "%H:%M").time():
                status = "Late"
            else:
                status = "Absent"
        else:
            status = "Absent"

        results.append([date_str, sid, name, status])

    df_result = pd.DataFrame(results, columns=["Date", "ID", "Name", "Status"])
    df_result.to_csv(output_path, index=False)
    print(f"✅ Saved: {output_path}")

def analyze_all_logs():
    log_folder = f"{base_path}/logs"
    for file in sorted(os.listdir(log_folder)):
        if file.endswith(".csv"):
            date = file.replace(".csv", "")
            analyze_attendance_for_date(date)

# Run the agent
analyze_all_logs()

from google.colab import files
files.download("Attendance_Tracker/output/2025-06-20_attendance.csv")
files.download("Attendance_Tracker/output/2025-06-21_attendance.csv")
files.download("Attendance_Tracker/output/2025-06-22_attendance.csv")